repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.280
    hooks:
      - id: ruff

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
